# Default properties
# All properties can be overriden by equivalent env variables
# env vars can match case or be upper-case, eg.
# cluster_name and CLUSTER_NAME will be checked

browser_config:
    # cluster name
    cluster_name: 'browsers'

    # network to add browser containers to
    # default bridge network
    network_name: 'bridge'

    # Max simultaneous containers that can be used
    max_containers: 10

    # max duration of the container
    container_expire_secs: 86400000

    # duration to keep `reqid` around
    # from time of request to initialization
    init_req_expire_secs: 300

    # time to store entries in the queue
    queue_expire_secs: 60

    # frequency of checking and removing expired containers
    remove_expired_secs: 30


    # THROTTLING
    # ==========
    # avg above which to start throttling
    throttle_max_avg: 1.0

    # number of samples
    throttle_samples: 10
    # how long to keep throttle samples around
    throttle_expire_secs: 30

    #scale max_containers automatically based on avail cpus
    #cpu_auto_adjust: 5.5

    # ==============
    api_version: '1.24'

    # container ports to map
    ports:
        vnc: 6080
        cmd: 6082

    browser_image_prefix: oldwebtoday/

    browser_volumes: ''
    shm_size: 1g

    label_name: wr.shepherd_name
    label_browser: wr.name
    label_prefix: wr.

    default_browser: chrome


